### ISSUE TITLE
Retry requests when they fail (for Natty in particular)

### ISSUE THREAD

**Issue by rjrudman** [SOBotics/AdvancedFlagging#22]
Context:

https://chat.stackoverflow.com/transcript/message/41891835#41891835

**Comment by BaumMitAugen** [comment]
As someone who does most of his reviews in bulk, this would be rather important to me.

As it stands, this is sufficiently disruptive to make me use (the generally inferior) Natty reporter. ~50% of the posts won't feedback properly as it stands if one opens a batch.

**Comment by rjrudman** [comment]
Fixed in v0.5.59

**Comment by BaumMitAugen** [comment]
I still receive errors of the form

```
 uncaught exception: Failed to retrieve natty report: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

```

when opening a batch of reports in FF60/Tampermonkey on x86_64 Linux.

A Natty icon does not appear on the failed posts; trying to send feedback causes a red error popup "Failed to send feedback to Natty.".

Steps to reproduce: open a non-tiny batch of reports like https://reports.sobotics.org/r/KOpt63 with the 'Open all' link.

**Comment by BaumMitAugen** [comment]
I'm not sure if it's relevant, but https://github.com/SOBotics/Natty/issues/29 might make this whole query business obsolete anyway.

**Comment by rjrudman** [comment]
@BaumMitAugen  Indeed, it'll fix your particular case. However, the natty icon will still not show without fixing the root cause

**Comment by rjrudman** [comment]
There's no way to detect it just from the page. However, we *could* have a script which would only run on the open reports site which caches each answer as 'reported' by natty. However, that may cause issues as Natty isn't the only bot that generates reports there I believe.

**Comment by BaumMitAugen** [comment]
I was thinking about referrers or URL parameters added through the reports page; but as I said, that was just uneducated guessing.

Regarding the problem with different bots, we can probably just add an API parameter for the creation route I suppose.

**Comment by rjrudman** [comment]
It's definitely something we can look at, but I think it'll just avoid the problem rather than solve it.. as we can have bulk pages opened at once from different sources. I've just pushed update 0.5.61 which will only initialize the page when focused or on mouse move. Hopefully this'll solve the problem altogether!

**Comment by BaumMitAugen** [comment]
The updated version seems to work perfectly. Thank you!
